force-app/main/default/objects/Clienteling_Config__c/Clienteling_Config__c.object-meta.xml
<CustomObject>
    <label>Clienteling Config</label>
    <nameField>
        <label>Clienteling Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clienteling Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IDO_upsell_product__c/IDO_upsell_product__c.object-meta.xml
<CustomObject>
    <label>Product recommendation</label>
    <nameField>
        <label>Product recommendation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product recommendations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IDO_upsell_product__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Product recommendations</relationshipLabel>
    <relationshipName>Product_recommendations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/IDO_Wish_List__c/IDO_Wish_List__c.object-meta.xml
<CustomObject>
    <label>Wish List</label>
    <nameField>
        <label>Wish List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wish Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IDO_Wish_List__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Wish Lists</relationshipLabel>
    <relationshipName>Wish_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_History__c/Purchase_History__c.object-meta.xml
<CustomObject>
    <label>Purchase History</label>
    <nameField>
        <label>Purchase History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_History__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Purchase History</relationshipLabel>
    <relationshipName>Purchase_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/clientTestDataFactory.cls
@isTest

public class clientTestDataFactory {

    // Creates but does not insert a client config record
    public static Clienteling_Config__c createConfig() {
        Clienteling_Config__c config = new Clienteling_Config__c(
            Name = 'Test Config',
            Active__c = true
        );
        return config;

    }

    // Creates but does not insert a contact
    public static Contact createContact() {
        Contact con = new Contact(
            LastName = 'Bailey'
        );
        return con;

    }

    public static List < Task > createListTasks() {

        List < Task > testTASKS = new List < Task > ();

        // create list of tasks //
        for (Integer i = 0; i < 3; i++) {
            Task testTASK = new Task(
                Subject = 'Call' + i,
                Status = 'Completed',
                Priority = 'High'
            );
            testTASKS.add(testTASK);
        }
        insert testTASKS;
        return testTASKS;

    }

    public static List < Purchase_History__c > createPurchases(Id theCustomer) {

        List < Purchase_History__c > testPurchases = new List < Purchase_History__c > ();

        // create list of Purchase_History__c //
        for (Integer i = 0; i < 3; i++) {
            Purchase_History__c purch = new Purchase_History__c(
                Name = 'Test' + i,
                Customer__c = theCustomer
            );
            testPurchases.add(purch);
        }
        insert testPurchases;
        return testPurchases;

    }

    public static List < IDO_Wish_List__c > createWishlists(Id theCustomer) {

        List < IDO_Wish_List__c > testWishlists = new List < IDO_Wish_List__c > ();

        // create list of IDO_Wish_List__c //
        for (Integer i = 0; i < 3; i++) {
            IDO_Wish_List__c wish = new IDO_Wish_List__c(
                Name = 'Test' + i,
                Customer__c = theCustomer
            );
            testWishlists.add(wish);
        }
        insert testWishlists;
        return testWishlists;

    }

    public static List < IDO_upsell_product__c > createRecommended(Id theCustomer) {

        List < IDO_upsell_product__c > testRecos = new List < IDO_upsell_product__c > ();

        // create list of IDO_upsell_product__c //
        for (Integer i = 0; i < 3; i++) {
            IDO_upsell_product__c reco = new IDO_upsell_product__c(
                Name = 'Test' + i,
                Customer__c = theCustomer
            );
            testRecos.add(reco);
        }
        insert testRecos;
        return testRecos;

    }

}