force-app/main/default/objects/Clienteling_Config__c/Clienteling_Config__c.object-meta.xml
<CustomObject>
    <label>Clienteling Config</label>
    <nameField>
        <label>Clienteling Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clienteling Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clienteling_Config__c/fields/Logo__c.field-meta.xml
<CustomField>
    <fullName>Logo__c</fullName>
    <inlineHelpText>Name of the static resource you uploaded the image to.</inlineHelpText>
    <label>Logo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clienteling_Config__c/fields/Logo_Height__c.field-meta.xml
<CustomField>
    <fullName>Logo_Height__c</fullName>
    <inlineHelpText>Number in px&apos;s - i.e. &apos;40&apos;</inlineHelpText>
    <label>Logo Height</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Clienteling_Config__c/fields/Logo_Width__c.field-meta.xml
<CustomField>
    <fullName>Logo_Width__c</fullName>
    <inlineHelpText>Number in px&apos;s - e.g. &apos;200&apos;</inlineHelpText>
    <label>Logo Width</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/clientelingGetConfig.cls
public with sharing class clientelingGetConfig {

    @AuraEnabled(cacheable = true)
    public static Clienteling_Config__c getConfig() {
        system.debug('getConfig running..');

        Clienteling_Config__c conf = [SELECT Active__c, Id, Logo_Height__c, Logo_Width__c, Logo__c, Name
            FROM Clienteling_Config__c WHERE Active__c = true ORDER BY LastModifiedDate LIMIT 1
        ];
        system.debug('the config details: ' + conf);
        return conf;
    }
}